"""Add Emoji Column

Revision ID: b677918c75c7
Revises: b6b6dda5b184
Create Date: 2022-07-21 13:31:59.563800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b677918c75c7'
down_revision = 'b6b6dda5b184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_categories', sa.Column('emoji', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_categories', 'emoji')
    # ### end Alembic commands ###
